name: all topics


on:
 workflow_dispatch:


jobs:
  hello:
   runs-on: ubuntu-latest

   env:
    APP_NAME: dolly_App
    ENVIRONMENT: dev

   steps:
    - name: Running ENVIRONMENT
      run: echo "My Application name is $APP_NAME and env is $ENVIRONMENT"


     
    


