name: My first workflow



on:
 push:
  branches:
    - main



jobs:
   hello:
     runs-on: ubuntu-latest



     steps:
      - name: testing
        run: echo "Runing Test"

   build:
     needs: hello
     runs-on: ubuntu-latest

     steps:
      - name: bulding
        run: echo Building"
 
       
   deploying:
     need: build
     runs-on: ubutnu-latest

     steps:
       - name: deploying
         run: echo "deploying"
     





