name: Env demo


on:
  workflow_dispatch:


jobs:
  demo:
    runs-on: ubuntu-latest


    env:
      APP_NAME: my-app
      ENVIRONMENT: dev



    steps:
      - name: print variables
        run: |
          echo "Application: $APP_NAME"
          echo "environment: $ENVIRONMENT"



