name: github contexts



on:
 workflow_dispatch:

jobs:
  demo-context:
   runs-on: ubuntu-latest


steps:
   - name: print context information
     run: |
       echo "Actor : ${{ github.actor }}"
       echo "repository : ${{ github.repository }}"
       echo "branch : ${{ github.ref }}"
       echo "commit : ${{ github.sha }}"
       echo "Event : ${{ github.event_name }}"
       
  



