name: if condition



on:
  push:
    branches:
      - main


jobs:
  demo_if:
    runs-on: ubuntu-latest
    
    steps:
      - name: If condition runnin
        if: github.event_name == 'push'
        run: echo "Deploying"






